name: Create Cluster Preview

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  preview:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --file Dockerfile --tag docker.io/aslakknutsen/istio-workspace-ci-demo:${{GITHUB_SHA}}
