name: Create Cluster Preview

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

jobs:

  preview:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag docker.io/aslakknutsen/istio-workspace-ci-demo:${{ github.sha }}
        docker push docker.io/aslakknutsen/istio-workspace-ci-demo:${{ github.sha }}
    - name: Deploy preview
      uses: aslakknutsen/istio-workspace-action@master
      if: contains(join(github.event.pull_request.labels.*.name), 'preview') 
      with:
        action: create
        server: ${{ secrets.K8S_API_SERVER }}
        token: ${{ secrets.K8S_TOKEN }}
        namespace: aslak-devconf
        session: ${{ github.head_ref }}
        deployment: ratings-v1
        route: header:x-test-suite=aslak
        image: docker.io/aslakknutsen/istio-workspace-ci-demo:${{ github.sha }}
    - name: Sleep
      run: sleep 10
    - name: Undeploy preview
      uses: aslakknutsen/istio-workspace-action@master
      if: !contains(join(github.event.pull_request.labels.*.name), 'preview')
      with:
        action: delete
        server: ${{ secrets.K8S_API_SERVER }}
        token: ${{ secrets.K8S_TOKEN }}
        namespace: aslak-devconf
        session: ${{ github.head_ref }}
        deployment: ratings-v1
