name: Create Cluster Preview

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  preview:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --file Dockerfile --tag docker.io/aslakknutsen/istio-workspace-ci-demo:$GITHUB_SHA
        docker push docker.io/aslakknutsen/istio-workspace-ci-demo:$GITHUB_SHA
    - name: Deploy preview
      uses: docker://docker.io/aslakknutsen/istio-workspace:latest
      with:
        entrypoint: ike
        args: create -s $GITHUB_BRANCH -n aslak-devconf --route header:x-test-suite=aslak -d ratings-v1 -i docker.io/aslakknutsen/istio-workspace-ci-demo:$GITHUB_SHA