name: Create Cluster Preview

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  preview:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --file Dockerfile --tag docker.io/aslakknutsen/istio-workspace-ci-demo:$GITHUB_SHA
        docker push docker.io/aslakknutsen/istio-workspace-ci-demo:$GITHUB_SHA
    - name: Deploy preview
      uses: docker://docker.io/aslakknutsen/istio-workspace:latest
      env:
        ACTION: create
        SERVER: ${{ secrets.K8S_API_SERVER }}
        TOKEN: ${{ secrets.K8S_TOKEN }}
        IKE_NAMESPACE: aslak-devconf
        IKE_SESSION: ${{ github.head_ref }}
        IKE_DEPLOYMENT: ratings-v1
        IKE_ROUTE: header:x-test-suite=aslak
        IKE_IMAGE: docker.io/aslakknutsen/istio-workspace-ci-demo:${{ github.sha }}
      with:
        entrypoint: ike_actions.sh
    - name: Sleep
      run: sleep 11
    - name: Deploy remove
      uses: docker://docker.io/aslakknutsen/istio-workspace:latest
      env:
        ACTION: delete
        SERVER: ${{ secrets.K8S_API_SERVER }}
        TOKEN: ${{ secrets.K8S_TOKEN }}
        IKE_NAMESPACE: aslak-devconf
        IKE_SESSION: ${{ github.head_ref }}
        IKE_DEPLOYMENT: ratings-v1
      with:
        entrypoint: ike_actions.sh        