name: Create Cluster Preview

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  preview:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --file Dockerfile --tag docker.io/aslakknutsen/istio-workspace-ci-demo:$GITHUB_SHA
    - name: Deploy preview
      image: docker.io/aslakknutsen/istio-workspaces:latest
      entrypoint: ike_actions.sh
      env:
        SERVER: ${{ secrets.K8S_API_SERVER }}
        TOKEN: ${{ secrets.K8S_TOKEN }}
        NAMESPACE: aslak-devconf
        ACTION: create
        SESSION: $GITHUB_BRANCH
        ROUTE: header:x-test-suite=aslak
        DEPLOYMENT: ratings-v1
        