name: UnDeploy Preview Service A

on:
  pull_request:
    types: [unlabeled]
    paths:
      - 'service-a/*'

jobs:

  preview-undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Undeploy preview
        uses: aslakknutsen/istio-workspace-action@master
        if: false == contains(join(github.event.pull_request.labels.*.name), 'preview')
        with:
          action: delete
          server: ${{ secrets.K8S_API_SERVER }}
          token: ${{ secrets.K8S_TOKEN }}
          config: service-a/.ike.config.yaml
          session: ${{ github.head_ref }}
