name: UnDeploy Preview Service B

on:
  pull_request:
    types: [unlabeled]

jobs:

  preview-undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Undeploy preview
        uses: aslakknutsen/istio-workspace-action@master
        working-directory: service-b
        if: false == contains(join(github.event.pull_request.labels.*.name), 'preview')
        with:
          action: delete
          server: ${{ secrets.K8S_API_SERVER }}
          token: ${{ secrets.K8S_TOKEN }}
          session: ${{ github.head_ref }}
